# Generated by Django 5.0.2 on 2024-03-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_trail_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
