# Generated by Django 5.0.2 on 2024-03-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_trail_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MagicPage',
            new_name='athlete',
        ),
    ]
